-- =====================================================================
-- 81 - BERSIHKAN DATA AUTO-SYNC TIKTOK (TAP) TAHAP 2
-- Tanggal : 2026-10-08
--
-- TUJUAN:
--   Membersihkan sisa 886 order TAP yang baru masuk akibat sync manual
--   sebelum tombol terkunci.
--
-- JAMINAN KEAMANAN:
--   1. Backup snapshot baru:
--      _backup_sales_sebelum_clean_tap_v2
--      _backup_organic_videos_sebelum_clean_tap_v2
--   2. Data Excel manual (attribution_type IS DISTINCT FROM 'TAP') UTUH (25.344 baris).
--   3. Tabel 'videos' (PIC) dan 'ads_performance' (Ads) UTUH.
--   4. Guard assertion: jika data Excel berkurang 1 saja -> otomatis ROLLBACK.
-- =====================================================================

\pset pager off
\set ON_ERROR_STOP on

BEGIN;

-- 1. Buat Tabel Backup Baru untuk Snapshot Sekarang
DROP TABLE IF EXISTS _backup_sales_sebelum_clean_tap_v2;
DROP TABLE IF EXISTS _backup_organic_videos_sebelum_clean_tap_v2;

CREATE TABLE _backup_sales_sebelum_clean_tap_v2 AS SELECT * FROM sales;
CREATE TABLE _backup_organic_videos_sebelum_clean_tap_v2 AS SELECT * FROM organic_videos;

-- 2. Guard: Pastikan Backup v2 Sukses
DO $$
DECLARE
  v_s_orig bigint; v_s_bk bigint;
  v_o_orig bigint; v_o_bk bigint;
BEGIN
  SELECT count(*) INTO v_s_orig FROM sales;
  SELECT count(*) INTO v_s_bk FROM _backup_sales_sebelum_clean_tap_v2;
  SELECT count(*) INTO v_o_orig FROM organic_videos;
  SELECT count(*) INTO v_o_bk FROM _backup_organic_videos_sebelum_clean_tap_v2;

  IF v_s_orig <> v_s_bk THEN
    RAISE EXCEPTION 'GUARD GAGAL: Backup sales v2 (%) tidak sama dengan aslinya (%)', v_s_bk, v_s_orig;
  END IF;

  IF v_o_orig <> v_o_bk THEN
    RAISE EXCEPTION 'GUARD GAGAL: Backup organic_videos v2 (%) tidak sama dengan aslinya (%)', v_o_bk, v_o_orig;
  END IF;

  RAISE NOTICE 'Backup v2 aman: sales = % baris, organic_videos = % baris', v_s_bk, v_o_bk;
END $$;

-- 3. Catat Baseline Data Non-TAP (Data Excel, Videos PIC, Ads)
CREATE TEMP TABLE _baseline_protect AS
SELECT
  (SELECT count(*) FROM sales WHERE attribution_type IS DISTINCT FROM 'TAP') AS excel_sales_count,
  (SELECT count(*) FROM videos) AS pic_videos_count,
  (SELECT count(*) FROM ads_performance) AS ads_count;

-- 4. Hapus Data Auto-Sync TAP dari Tabel sales
DELETE FROM sales 
WHERE attribution_type = 'TAP';

-- 5. Hapus Data Auto-Sync dari organic_videos
DELETE FROM organic_videos 
WHERE raw_data->>'autoGeneratedFromOrder' IS NOT NULL
   OR (raw_data->>'view_count' IS NOT NULL AND raw_data->>'source_url' IS NOT NULL);

-- 6. Guard: Pastikan Data Excel & Master Lain Tidak Berkurang Sedikit Pun
DO $$
DECLARE
  v_excel_now bigint;
  v_pic_now bigint;
  v_ads_now bigint;
  v_excel_base bigint;
  v_pic_base bigint;
  v_ads_base bigint;
BEGIN
  SELECT count(*) INTO v_excel_now FROM sales WHERE attribution_type IS DISTINCT FROM 'TAP';
  SELECT count(*) INTO v_pic_now FROM videos;
  SELECT count(*) INTO v_ads_now FROM ads_performance;

  SELECT excel_sales_count, pic_videos_count, ads_count 
  INTO v_excel_base, v_pic_base, v_ads_base 
  FROM _baseline_protect;

  IF v_excel_now <> v_excel_base THEN
    RAISE EXCEPTION 'GUARD GAGAL: Data sales Excel berubah dari % menjadi %!', v_excel_base, v_excel_now;
  END IF;

  IF v_pic_now <> v_pic_base THEN
    RAISE EXCEPTION 'GUARD GAGAL: Data videos PIC berubah dari % menjadi %!', v_pic_base, v_pic_now;
  END IF;

  IF v_ads_now <> v_ads_base THEN
    RAISE EXCEPTION 'GUARD GAGAL: Data ads_performance berubah dari % menjadi %!', v_ads_base, v_ads_now;
  END IF;

  RAISE NOTICE 'Guard lolos: Seluruh data Excel (%), Videos PIC (%), dan Ads (%) UTUH 100%%', v_excel_now, v_pic_now, v_ads_now;
END $$;

COMMIT;

-- 7. Laporan Hasil Pembersihan
SELECT 'sales (Data Excel Murni)' AS tabel, count(*) AS sisa_baris FROM sales
UNION ALL
SELECT 'organic_videos', count(*) FROM organic_videos
UNION ALL
SELECT 'videos (PIC)', count(*) FROM videos
UNION ALL
SELECT 'ads_performance (Ads)', count(*) FROM ads_performance;
